// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7gtgPiM4cbU7IkZ7X9JBe1I3dyTH2s5E',
    appId: '1:245162281677:android:ea10c16f85faacdb3eb784',
    messagingSenderId: '245162281677',
    projectId: 'mfm-triumphant-church-apps',
    storageBucket: 'mfm-triumphant-church-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDikjAJ2xY70bIf6vWEZvjet7OiFfrtW1o',
    appId: '1:160642673140:ios:5d0162052e7b55088771a1',
    messagingSenderId: '160642673140',
    projectId: 'mychurch-3a9c9',
    databaseURL: 'https://mychurch-3a9c9.firebaseio.com',
    storageBucket: 'mychurch-3a9c9.firebasestorage.app',
    androidClientId:
        '160642673140-urphgsshc2n4mvrn6236j811d5nipr2c.apps.googleusercontent.com',
    iosBundleId: 'apps.envisio',
  );
}
